<?php

namespace AppBundle\Repository;

/**
 * DiscordUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscordUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserByToken($token)
    {
        return $this->createQueryBuilder('u')
                    ->innerJoin('u.token', 't')
                    ->addSelect('t')
                    ->where('t.token = :token')
                    ->setParameter('token', $token)
                    ->getQuery()
                    ->getOneOrNullResult();
    }

    public function findOneBy(array $criteria, array $orderBy = null)
    {
        if (count($criteria) === 1 && isset($criteria['token'])) {
            return $this->getUserByToken($criteria['token']);
        } else {
            return parent::findOneBy($criteria, $orderBy);
        }
    }
}
