<?php

namespace AppBundle\Repository;

/**
 * DiscordUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscordUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserByToken($token)
    {
        return $this->createQueryBuilder('u')
                    ->innerJoin('u.token', 't')
                    ->addSelect('t')
                    ->where('t.token = :token')
                    ->setParameter('token', $token)
                    ->getQuery()
                    ->getOneOrNullResult();
    }
}
